from setuptools import setup, find_packages

setup(
    name="Wi-Fi audit tool",
    version="1.1",
    description="Wi-Fi auditing and monitoring tool",
    python_requires=">=3.11",
    packages=find_packages(),
    install_requires=[
        "aiohttp",
        "certifi",
        "colorama",
        "cryptography",
        "docutils",
        "geographiclib",
        "geopy",
        "haversine",
        "IPython",
        "jinja2",
        "keyring",
        "numba",
        "numpy",
        "pandas",
        "Pillow",
        "psutil",
        "pytest",
		"python-nmap",
        "pytz",
        "redis",
        "requests",
        "requests-oauthlib",
        "scipy",
        "setuptools",
        "tqdm",
        "urllib3",
        "wheel",
        "wmi",
        "yarl"
    ],
)
